---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-cert-apps
spec:
  project: default
  source:
    repoURL: https://github.com/sugardon-org/kubernetes-cert
    targetRevision: main
    path: argocd-apps/overlays/sugardon01
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
