---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-secret-apps
  namespace: sealed-secrets
spec:
  project: default
  source:
    repoURL: https://github.com/sugardon-org/kubernetes-secret
    targetRevision: main
    path: argocd-apps/overlays/sugardon01
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
