---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helmfile-argocd-sugardon01
resources:
  - kubernetes-secret.yaml
  - tekton-cicd.yaml
  - ../../base

patches:
  - path: namespace-path.json
    target:
      kind: Application
