---
# https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tekton-cicd
spec:
  description: "sugardon-org/tekton-cicd project"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-cicd-apps
spec:
  project: tekton-cicd
  source:
    repoURL: https://github.com/sugardon-org/tekton-cicd
    targetRevision: main
    path: argocd-apps/overlays/sugardon01
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
