---
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '*.gotmpl'

ignore: |
    .github/
    *-secrets.yaml
rules:
  # 120 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 160
    level: warning
