---
environments:
  sugardon01:

---
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: argo
    url: https://argoproj.github.io/argo-helm

---
helmfiles:
  - ./argo-cd/helmfile.yaml
