---
environments:
  sugardon01:
    secrets:
      - environments/sugardon01/argo-cd-secrets.yaml

---
releases:
  # Published chart example
  - name: helmfile-argocd-{{ .Environment.Name }}
    namespace: helmfile-argocd-{{ .Environment.Name }}
    createNamespace: true
    chart: argo/argo-cd
    version: 2.9.3
    values:
      - environments/{{ .Environment.Name }}/argo-cd-values.yaml.gotmpl
      # disable because cf. https://github.com/helm/helm/issues/8615
      # use
      # $ helmfile -e sugardon01 template
      - environments/{{ .Environment.Name }}/applications.yaml.gotmpl
