---
environments:
  default:
    secrets:
    - environments/default/argo-cd-secrets.yaml

---
releases:
  # Published chart example
  - name: helmfile-argocd-{{ .Environment.Name }}
    namespace: helmfile-argocd-{{ .Environment.Name }}
    createNamespace: true
    chart: argo/argo-cd
    version: 2.9.3
    values:
      - environments/{{ .Environment.Name }}/argo-cd-values.yaml.gotmpl
