---
environments:
  sugardon01:
    secrets:
      - environments/sugardon01/argo-cd-secrets.yaml
  sugardon02:
    secrets:
      - environments/sugardon02/argo-cd-secrets.yaml

---
releases:
  # Published chart example
  - name: helmfile-argocd-{{ .Environment.Name }}
    namespace: helmfile-argocd-{{ .Environment.Name }}
    createNamespace: true
    chart: argo/argo-cd
    version: 3.3.5
    values:
      - environments/{{ .Environment.Name }}/argo-cd-values.yaml.gotmpl
  - name: helmfile-argocd-{{ .Environment.Name }}-applications
    # TODO: prepare sugardon02
    # chart: ./applications/overlays/{{ .Environment.Name }}
    chart: ./applications/overlays/sugardon01
