---
name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-helmfile:
    name: Deploy Helmfile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      HELMFILE_ENV: sugardon01

    steps:
      - uses: actions/checkout@v3

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
      - name: Setup and Check GPG
        run: |
          export GPG_TTY=$(tty)
          gpg --pinentry-mode loopback --passphrase ${{ secrets.PASSPHRASE }} --export-secret-keys > ~/.gnupg/secring.gpg

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helmfile-version: v0.144.0
      - name: Show helmfile, helm and kubectl
        run: |
          helmfile --version
          helm version
          kubectl version --client
      - name: Uninstall default plugin
        run: |
          helm plugin uninstall diff
      - name: Setup dependency
        run: |
          make install-plugin
          make add-repo

      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: ${{ secrets.KUBECONTEXT }}

      #- name: Show diff
      #  run: helmfile -e $HELMFILE_ENV diff

      - name: helmfile sync
        run: helmfile -e $HELMFILE_ENV sync

