---
name: CI

on: [push, pull_request]

jobs:
  helmfile-check:
    name: Check Helmfile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
      - name: Setup and Check GPG
        run: |
          export GPG_TTY=$(tty)
          gpg --pinentry-mode loopback --passphrase ${{ secrets.PASSPHRASE }} --export-secret-keys > ~/.gnupg/secring.gpg

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.3.0
        with:
          helmfile-version: v0.157.0
      - name: Show helmfile, helm and kubectl
        run: |
          helmfile --version
          helm version
          kubectl version --client
      - name: Uninstall default plugin
        run: |
          helm plugin uninstall diff
      - name: Setup dependency
        run: |
          make install-plugin
          make add-repo
      - name: lint helmfile
        run: |
          make helmfile-lint

  yaml-check:
    name: Check with yamllint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
      - name: yamllint
        run: |
          make yamllint
